### ISSUE TITLE
return just the render method?

### ISSUE THREAD

**Issue by millermedeiros** [millermedeiros/requirejs-hogan-plugin#1]
I never really needed to access the other properties of the `Template` besides `render()` I guess it would be better to simply return the `render()` method so it could be used like this:

``` js
define(['hgn!foo'], function(foo){
  console.log( foo({lorem:"ipsum"}) );
});
```

**Comment by mattdeclaire** [comment]
I found this feature confusing.  I was expecting back vanilla `Hogan.Template` objects.  I'm loading a bunch of templates into a map, and trying to send them as partials into `render()` calls.  I see you have a workaroundin #7, but that means remapping all my partials each time.

I ended up reverting the templates myself:

``` js
$.each(templates, function(name, template) {
    templates[name] = template.template;
});
```

I realize changing this now would break existing code, but could you add a config flag to remove this feature?
