### ISSUE TITLE
Please tag latest revision

### ISSUE THREAD

**Issue by gxxcastillo** [millermedeiros/requirejs-hogan-plugin#9]
Sorry, lame ticket, I know, but I'm installing requirejs-hogan-plugin as a Bower dependency and I need some of the latest fixes.

Unfortunately, Bower does not yet support installing non-tagged revisions of a package so I can only install ver0.2.0.  (hopefully this will be changed soon: https://github.com/twitter/bower/issues/107 )

If its not too much trouble would you mind creating a ver0.2.1 tag for the latest revision?

**Comment by millermedeiros** [comment]
just pushed new tag v0.2.1 - thx!

**Comment by gxxcastillo** [comment]
Thanks :)
